Use supported ES6 destructuring statement
Although it is legal ES6 syntax, Node v5.3.0 even with
--harmony_destructuring (marked as "in progress") fails at:

src/transforms/framing.js:42
      ({ value, size, error } = readVarInt(this.buffer, offset) || { error: "Not enough data" });
       ^^^^^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/admin/games/voxeljs/node-minecraft-protocol/src/client.js:6:15)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)

The `let { value, size, error } = ` form works, use it instead here.